sonar.projectKey=shayaanhu_devsecops-secure-app-pipeline
sonar.organization=shayaanhu
sonar.projectName=UniRide

sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/Migrations/**,**/obj/**,**/bin/**,**/*.db,**/*.db-shm,**/*.db-wal
